# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 052a4bfbd676b32cf0d167583d3d8cc07ec74a5253a12808d9107842bdbccc5a300e6a3f05036f24c41ab44559cdee1084e57d9d9b4a10eea0e67ec2fee77086

test:
  secret_key_base: 09bcd13543474e71dc0a46c5339905559fd68584596a3e6c77ddabb9a2fb13b523119e5c0d266491fab9d91ef78dca7e9fbc448a7dd65d8ef465fde5d65fdcd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
